### ISSUE TITLE
Update Pan Docs link

### ISSUE THREAD

**Issue by JL2210** [ahrnbom/gbapfomgd#10]
The book currently refers to http://gbdev.gg8.se/wiki/articles/Pan_Docs, while the most up-to-date version of Pan Docs is at https://gbdev.io/pandocs/.

**Comment by ahrnbom** [comment]
Actually, I think this is even more up to date:

https://github.com/gbdev/pandocs

Edit: Nevermind, that's just the source code.

**Comment by JL2210** [comment]
It's the same thing. https://gbdev.io/pandocs/ is rendered from
https://github.com/gbdev/pandocs/

**Comment by ahrnbom** [comment]
Fixed as of 1.5
