### ISSUE TITLE
Small typo in 3.8 RAM

### ISSUE THREAD

**Issue by Glerek** [ahrnbom/gbapfomgd#14]
> Then, two write the vector (5, 3)

should read as 

> Then, to write the vector (5, 3)

Thanks a lot for writing this document, I just started learning ASM for gameboy and it helps a lot!

**Comment by ahrnbom** [comment]
Thanks for noticing this minor error! This will be fixed shortly

**Comment by ahrnbom** [comment]
Fixed as of 22986d0
