### ISSUE TITLE
Can you host this pdf on github pages for convenience please?

### ISSUE THREAD

**Issue by lesleyrs** [ahrnbom/gbapfomgd#15]

**Comment by ahrnbom** [comment]
Good idea! This is my first time using Github Pages, but going to https://ahrnbom.github.io/gbapfomgd/ seems to work for me now.

**Comment by lesleyrs** [comment]
It's a little buggy but it works thanks a lot! On chrome there's 2 scroll bars, 1 for the pdf and 1 for the page itself, and the link on the top right is broken.

Btw it would be nice if you can put the link in either about or readme
