### ISSUE TITLE
Backslashes before percent signs in examples

### ISSUE THREAD

**Issue by ISSOtm** [ahrnbom/gbapfomgd#5]
The following two percent signs are (rightfully) escaped, but the backslashes do show up in output (page 33). Not sure how to fix.

https://github.com/ahrnbom/gbapfomgd/blob/adc2dc8c6ae4a6922e583ac695367b6a46cd63dc/gbasmdev.tex#L609-L612

https://github.com/ahrnbom/gbapfomgd/blob/adc2dc8c6ae4a6922e583ac695367b6a46cd63dc/gbasmdev.tex#L616-L619

**Comment by ahrnbom** [comment]
The `code` environment takes care of escaping `%` characters, so these backslashes are just errors. I'll fix this.

**Comment by ahrnbom** [comment]
This is fixed as of 544881a
