### ISSUE TITLE
Book companion binaries for Windows?

### ISSUE THREAD

**Issue by eried** [ahrnbom/gbapfomgd#6]
After reading the book (it is brief and awesome! thanks), I was trying to compile some examples, but few tools: i.e. _mod2gbt_, comes as sourcecode... and this becomes a PITA

It would be nice to have a zip file with everything needed to start hacking some asm examples in Windows, without having to look for individual pieces or compile anything

**Comment by ahrnbom** [comment]
Hi! I'm glad you enjoyed the book.

First of all, you do not need GBT-Player to use GingerBread (you're not the first to make this mistake, so I guess it should be clarified somewhere), and the included examples compile fine without it (just without music). So there's no need to compile anything before you start hacking. To compile the examples without GBT-Player, you just need to modify the line
`set "include_gbt=1"` to `set "include_gbt="` in assemble.bat and comment out the line `USE_GBT_PLAYER EQU 1` in example.asm. If you're making your own games from scratch with GingerBread, you don't need to change *anything*, as GingerBread doesn't rely on GBT-Player for anything whatsoever.

Second, if binaries for GBT-Player should be made available somewhere for different platforms, I don't think it's this book's job to do so. Perhaps it could be connected to the GingerBread repo, but I think it's out of scope; it really doesn't have anything to do with GingerBread itself, and any GBT-Player users who aren't using GingerBread would have no easy way to find it. In addition, should GingerBread include a full Python environment too, just to allow the sgb_border.py script to run without any dependencies? And if binaries for Windows were to be included, why not MacOS or various Linux variants? 

My suggestion is that you open an issue on https://github.com/AntonioND/gbt-player and kindly ask for official binaries there. That way, any GBT-Player users can take advantage of it. In the meantime, I suggest you start coding in GingerBread without GBT-Player. If, for whatever reason, you do not get GBT-Player to run, you can simply produce music for your games in some other way.

**Comment by eried** [comment]
Thanks for the comment, I will try to find a workaround with that info. 

> Second, if binaries for GBT-Player should be made available somewhere for different platforms, I don't think it's this book's job to do so. 

Yes, but you know how instant gratification works. Like if I am reading and there is a companion "compile_chapter_1_1.2_example.bat" (all this is hypotetical, I know you do not have lengthy examples yet) that generates a "example_1_1.2.gb" it would be super interactive, similar to old Visual Basic/ C# books with a companion diskette/CD.

> Perhaps it could be connected to the GingerBread repo, but I think it's out of scope; it really doesn't have anything to do with GingerBread itself, and any GBT-Player users who aren't using GingerBread would have no easy way to find it. In addition, should GingerBread include a full Python environment too, just to allow the sgb_border.py script to run without any dependencies? And if binaries for Windows were to be included, why not MacOS or various Linux variants?

That might be true, but Windows users are lazy :P 

Anyhow, thanks again for the book. Recently I got a gbxcart-rw and couple of pokemon clones to write, so that ignited my wish to learn hahah

**Comment by ahrnbom** [comment]
Closing because this is not something that I will fix. If you (or someone else) builds a .zip with whatever files you think would be helpful, I will gladly host it.

**Comment by eried** [comment]
I was thinking on something like this:
https://github.com/eried/gbapfomgd/tree/master/resources/windows

It is still missing a examples/ folder with relative paths so you just double click each example.asm and get the corresponding .gb

Do you use an specific editor? syntax highlighter?

**Comment by ahrnbom** [comment]
Including the resources _inside_ the book repo is, in my opinion, a **terrible** idea and I will never merge that. For example, the licenses need to be worked out. Currently, the entire repo is under a CC licence, which I don't think is compatible with _any_ of the things you included. I'm not even sure it's legal to redistribute BGB? It doesn't seem to be released under any license so your fork might actually be illegal as it is.  

In addition, git is just not a good system for distributing binaries. I think you'd be better off just uploading a .zip file somewhere.

I typically code in Gedit or Notepad++. They both have general purpose ASM-syntax highlighting, which isn't ideal.

**Comment by eried** [comment]
Yeah, I was not thinking on doing a PR with them. Initially I just wanted the typical _sneaky_ script that downloads the stuff instead; but some resources are updated via hand (the filenames are not consistent). I might move all to a torrent and just place the magnet link after adding examples and checking few editors/highlighters.
