### ISSUE TITLE
Invalid instructions used for examples

### ISSUE THREAD

**Issue by JL2210** [ahrnbom/gbapfomgd#7]
> In addition, `ld` can load from memory addresses using special syntax:
`ld [de], b` would copy the data from B onto a memory position specified by
the address stored on DE.

The only valid instructions containing `[de]` are `ld [de], a` and `ld a, [de]`.

> A hardcoded address can be used as well, like
`ld [$ff83], 255` which writes the number 255 to memory position `$FF83`.

An absolute address store can't have an immediate as the second operand. You'd be looking for `ld [n16], a`.

**Comment by ahrnbom** [comment]
Fixed as of 4639f0b. Thanks!
