### ISSUE TITLE
teamlampoil.se is down

### ISSUE THREAD

**Issue by JL2210** [ahrnbom/gbapfomgd#9]
It seems to load but says the connection is reset. It's linked to in the book and the README and this is the best place to report it as far as I can tell.

**Comment by ahrnbom** [comment]
I am aware! Currently looking into various options for a more robust web hosting solution.

**Comment by JL2210** [comment]
In the meantime could you please provide builds on the releases page?

**Comment by ahrnbom** [comment]
Good idea! I'll look into it.

**Comment by ahrnbom** [comment]
Version 1.4 is now available at https://github.com/ahrnbom/gbapfomgd/releases/tag/v1.4

**Comment by ilmalte** [comment]
It looks like someone has put it on web.archive.org, you can find it here:
https://web.archive.org/web/20200103160942/https://teamlampoil.se/book/gbasmdev.pdf

**Comment by JL2210** [comment]
That is still an old version, though. I prefer just to download the PDF
from Releases and view it locally.

**Comment by vertexmachina** [comment]
@JL2210 

You can use [this converter](https://cloudconvert.com/tex-to-pdf) to generate a PDF from the latest tex file: https://raw.githubusercontent.com/ahrnbom/gbapfomgd/master/gbasmdev.tex

(Although it doesn't seem to render the TOC properly so links to other chapters don't work.)

**Comment by ahrnbom** [comment]
As a workaround, I uploaded the Rope & Bombs game to itch.io and made http://teamlampoil.se point to that site. That site also mentions the book, with a link to GitHub. So for now, this GitHub page is the "official website" for the book. 

I'll update the book to not contain the direct download link for the book, which no longer works.
